// AUTO-GENERATED BY /lib/generateContentIndex.js

// Run "node src/lib/generateContentIndex.js" to generate


// ===== About =====
import { aboutContent } from "./info-pages/about/about";
import { causesContent } from "./info-pages/about/causes";
import { diagnosisContent } from "./info-pages/about/diagnosis";
import { symptomsContent } from "./info-pages/about/symptoms";
import { treatmentsContent } from "./info-pages/about/treatments";

// ===== Research =====
import { researchContent } from "./info-pages/research/research";

// ===== Resources =====
import { caregiverTipsContent } from "./info-pages/resources/caregiver-tips";
import { glossaryContent } from "./info-pages/resources/glossary";
import { mutualAidContent } from "./info-pages/resources/mutual-aid";
import { newlyDiagnosedContent } from "./info-pages/resources/newly-diagnosed";
import { resourcesContent } from "./info-pages/resources/resources";
import { specialistsContent } from "./info-pages/resources/specialists";
import { supplementsContent } from "./info-pages/resources/supplements";
import { supportGroupContent } from "./info-pages/resources/support-group";

// ===== About the Foundation =====
import { aboutTheFoundationContent } from "./info-pages/about-the-foundation/about-the-foundation";

// ===== Legal =====
import { accessibilityContent } from "./legal/accessibility";
import { disclaimerContent } from "./legal/disclaimer";
import { privacyPolicyContent } from "./legal/privacy-policy";
import { termsOfUseContent } from "./legal/terms-of-use";

// ===== Patient Stories =====
import { patientStoriesContent } from "./info-pages/resources/patient-stories/patient-stories";
import { mattKYContent } from "./info-pages/resources/patient-stories/matt-KY";
import { eliMNContent } from "./info-pages/resources/patient-stories/eli-MN";
import { kelseyNYContent } from "./info-pages/resources/patient-stories/kelsey-NY";

export const allContent = [
  // About
  ...[aboutContent],
  ...[causesContent],
  ...[diagnosisContent],
  ...[symptomsContent],
  ...[treatmentsContent],
  // About the Foundation
  ...[aboutTheFoundationContent],
  // Research
  ...[researchContent],
  // Resources
  ...[caregiverTipsContent],
  ...[glossaryContent],
  ...[mutualAidContent],
  ...[newlyDiagnosedContent],
  ...[resourcesContent],
  ...[specialistsContent],
  ...[supplementsContent],
  ...[supportGroupContent],
  // Legal
  ...[accessibilityContent],
  ...[disclaimerContent],
  ...[privacyPolicyContent],
  ...[termsOfUseContent],
  // Patient Stories
  ...[patientStoriesContent],
  ...[mattKYContent],
  ...[eliMNContent],
  ...[kelseyNYContent],
];
