// AUTO-GENERATED BY /lib/generateContentIndex.js

// Run "node src/lib/generateContentIndex.js" to generate


// ===== About =====
import { aboutContent } from "./info-pages/about/about";
import { causesContent } from "./info-pages/about/causes";
import { diagnosisContent } from "./info-pages/about/diagnosis";
import { symptomsContent } from "./info-pages/about/symptoms";
import { treatmentsContent } from "./info-pages/about/treatments";

// ===== Research =====
import { researchContent } from "./info-pages/research/research";

// ===== Resources =====
import { caregiverTipsContent } from "./info-pages/resources/caregiver-tips";
import { dictionaryContent } from "./info-pages/resources/dictionary";
import { mutualAidContent } from "./info-pages/resources/mutual-aid";
import { newlyDiagnosedContent } from "./info-pages/resources/newly-diagnosed";
import { resourcesContent } from "./info-pages/resources/resources";
import { specialistsContent } from "./info-pages/resources/specialists";
import { supplementsContent } from "./info-pages/resources/supplements";
import { supportGroupContent } from "./info-pages/resources/support-group";

// ===== Legal =====
import { accessibilityContent } from "./legal/accessibility";
import { disclaimerContent } from "./legal/disclaimer";
import { privacyPolicyContent } from "./legal/privacy-policy";
import { termsOfUseContent } from "./legal/terms-of-use";

// ===== Patient Stories =====
import { mattContent } from "./patient-stories/matt";

export const allContent = [
  // About
  ...[aboutContent],
  ...[causesContent],
  ...[diagnosisContent],
  ...[symptomsContent],
  ...[treatmentsContent],

  // Research
  ...[researchContent],

  // Resources
  ...[caregiverTipsContent],
  ...[dictionaryContent],
  ...[mutualAidContent],
  ...[newlyDiagnosedContent],
  ...[resourcesContent],
  ...[specialistsContent],
  ...[supplementsContent],
  ...[supportGroupContent],

  // Legal
  ...[accessibilityContent],
  ...[disclaimerContent],
  ...[privacyPolicyContent],
  ...[termsOfUseContent],

  // Patient Stories
  ...[mattContent],

];
